### ISSUE TITLE
Feature request: jump and cd

### ISSUE THREAD

**Issue by TD-Sky** [DreamMaoMao/searchjump.yazi#1]
Most of the uses I've found for searchjump are to jump on the directory and then go into it. I think it better to add an option `--cd` to combine the two steps: when running with `--cd`, searchjump will go into the item if it's a directory.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/DreamMaoMao/searchjump.yazi/assets/30348075/6da6f8a9-1477-404b-9d34-912fa088de97)
