### ISSUE TITLE
backspace not working

### ISSUE THREAD

**Issue by wohltat** [DreamMaoMao/searchjump.yazi#2]
Hi,

first thanks for the great plugin that was exactly what i was looking for.

I noticed that backspace is not working for stepping back a key. 
I guess this is missing if the plugin tries to be like neovims flash.

**Comment by DreamMaoMao** [comment]
dont in :
https://github.com/DreamMaoMao/searchjump.yazi/commit/180442113e7c8cf079076a6c36130539ec45456a

**Comment by DreamMaoMao** [comment]
fix a bug : 

https://github.com/DreamMaoMao/searchjump.yazi/commit/4eea2c96abb75a9d230acaf747f6c770a4d43a3f
